const ausgewählterText =
  "Die Geschichte beginnt in Ostdeutschland. Der Extremsportler Sven Ole Müller hatte sich zusammen mit Nicole Bauer, einer Marathonläuferin, in den Kopf gesetzt, an einem Radrennen in den USA teilzunehmen. Obwohl Nicole zum damaligen Zeitpunkt im grunde nie lange auf einem Rennrad gesessen hatte, willigte sie ein, mitzumachen. Bei dem Radrennen sollte es sich um das härteste Radrennen der Welt handeln, dem Race Across America, welches von der Westküste der USA bis zur Ostküste geht. Insgesamt sind somit 5.000 Kilometer zu absolvieren. Mit zwei weiteren Atlethen formierten sie sich zu einem Team zusammen und begannen mit dem Training. Wie aber geht man ein solches Projekt richtig an? Nicole stieß auf die Arbeiten des Neurobiologen Gerald Hüther, der sich bereit erklärte, unterstützend zur Seite zu stehen. So gab er immer wieder Denkanstöße, wie man ein funktionierendes Team aufbaut. Basis war seine Theorie des Gelingens, die auch in dem später veröffentlichten Buch 'Wie Träume wahr werden' von ihm dargelegt wurde. Sein Ansatz basiert auf dem Gedanken, dass es in einer immer komplexer werdenden Welt von größter Bedeutung ist, dass wir uns im Team wirkungs- und kraftvoll als Gestalter unseres Lebens definieren. Immer wieder gab es in den Vorbereitungen Probleme, die eine erfolgreiche Teilnahme am Radrennen in weite Ferne entschwinden ließen. Dies lag insbesondere daran, dass die Teammitglieder mehr als Einzelkämpfer unterwegs waren. Doch allmählich setzte sich die Erkenntnis durch, dass alle weiterkommen, wenn sie sich auf die anderen besinnen. So stieg die emotionale Verbindung zusehends und das Engagement und die Motivation ebenfalls. Nach elf Monaten Vorbereitung trat das Team im Juni 2016 in Ocenside, Kalifornien an den Start. Nun mussten sie beweisen, was sie konnten. Als unbekannte Außenseiter, ja mit teilweise arg geringer Rennraderfahrung, war bereits zweifelhaft, ob sie überhaupt am Ziel in Annapolis, Maryland ankommen würden. Rasch zeigte sich, welch menschliche Herausforderung dieser Sportevent war, der fast 10 Tage dauerte. Der Schweiß rann, die Muskeln schmerzten...doch dann geschah das Unfassbare. Das thüringische Außenseiterteam gewann das Rennen mit fünf Stunden Vorsprung vor dem Zweitplatzierten. Der Glaube an das Unmögliche hatte das scheinbar Unmögliche wahr werden lassen. Wenn Du mehr über die Theorie des Gelingens erfahren möchtest, empfehle ich Dir das Buch 'Wie Träume wahr werden' von Gerald Hüther.";
const synth = window.speechSynthesis;

const utterance = new SpeechSynthesisUtterance(
  ausgewählterText + window.getSelection()
);
utterance.lang = "de-DE";
function readAloud() {
  synth.speak(utterance);
  const btn1 = document.querySelector(".btn1");
  btn1.style.fontSize = "1.6rem";
  btn1.innerHTML = `<marquee direction="up" scrollamount="1" height="500"
        >Die Geschichte beginnt in Ostdeutschland.<br> Der Extremsportler Sven Ole Müller hatte sich zusammen mit Nicole Bauer, einer Marathonläuferin, in den Kopf gesetzt, an einem Radrennen in den USA teilzunehmen.<br> Obwohl Nicole zum damaligen Zeitpunkt im grunde nie lange auf einem Rennrad gesessen hatte, willigte sie ein, mitzumachen.<br><br> Bei dem Radrennen sollte es sich um das härteste Radrennen der Welt handeln, dem Race Across America, welches von der Westküste der USA bis zur Ostküste geht. Insgesamt sind somit 5.000 Kilometer zu absolvieren. <br><br>Mit zwei weiteren Atlethen formierten sie sich zu einem Team zusammen und begannen mit dem Training. <br><br>Wie aber geht man ein solches Projekt richtig an?<br> Nicole stieß auf die Arbeiten des Neurobiologen Gerald Hüther, der sich bereit erklärte, unterstützend zur Seite zu stehen. So gab er immer wieder Denkanstöße, wie man ein funktionierendes Team aufbaut. Basis war seine Theorie des Gelingens, die auch in dem später veröffentlichten Buch 'Wie Träume wahr werden' von ihm dargelegt wurde. Sein Ansatz basiert auf dem Gedanken, dass es in einer immer komplexer werdenden Welt von größter Bedeutung ist, dass wir uns im Team wirkungs- und kraftvoll als Gestalter unseres Lebens definieren. <br><br>Immer wieder gab es in den Vorbereitungen Probleme, die eine erfolgreiche Teilnahme am Radrennen in weite Ferne entschwinden ließen. Dies lag insbesondere daran, dass die Teammitglieder mehr als Einzelkämpfer unterwegs waren. Doch allmählich setzte sich die Erkenntnis durch, dass alle weiterkommen, wenn sie sich auf die anderen besinnen. So stieg die emotionale Verbindung zusehends und das Engagement und die Motivation ebenfalls.<br><br> Nach elf Monaten Vorbereitung trat das Team im Juni 2016 in Ocenside, Kalifornien an den Start. <br>Nun mussten sie beweisen, was sie konnten. Als unbekannte Außenseiter, ja mit teilweise arg geringer Rennraderfahrung, war bereits zweifelhaft, ob sie überhaupt am Ziel in Annapolis, Maryland ankommen würden. <br><br>Rasch zeigte sich, welch menschliche Herausforderung dieser Sportevent war, der fast 10 Tage dauerte. Der Schweiß rann, die Muskeln schmerzten.<br><br>..doch dann geschah das Unfassbare. Das thüringische Außenseiterteam gewann das Rennen mit fünf Stunden Vorsprung vor dem Zweitplatzierten. Der Glaube an das Unmögliche hatte das scheinbar Unmögliche wahr werden lassen. <br><br>Wenn Du mehr über die Theorie des Gelingens erfahren möchtest, empfehle ich Dir das Buch 'Wie Träume wahr werden' von Gerald Hüther.
        <br>Klicke nun rechts auf den "weiter"-Button.</marquee>`;
}
function stopReading() {
  synth.cancel();
  window.location = "tilly.html";
}
