const ausgewählterText =
  "The story begins in East Germany. Extreme athlete Sven Ole Müller, along with marathon runner Nicole Bauer, had set their minds on participating in a cycling race in the USA. Although Nicole had never really ridden a racing bike for long at the time, she agreed to participate. The race was to be the toughest cycling race in the world, the Race Across America, which runs from the west coast of the USA to the east coast. A total of 5,000 kilometers would be covered. They formed a team with two other athletes and began training. But how do you properly approach such a project? Nicole came across the work of neurobiologist Gerald Hüther, who agreed to provide support. He repeatedly offered food for thought on how to build a functioning team. The basis was his theory of success, which he also presented in his later book 'How Dreams Come True.' His approach is based on the idea that, in an increasingly complex world, it is of utmost importance that we define ourselves effectively and powerfully as a team, shaping our lives. Time and again, problems arose during the preparations that made a successful participation in the cycling race seem a distant prospect. This was primarily due to the fact that the team members were competing more as individual competitors. But gradually, the realization took hold that everyone would progress if they focused on each other. Thus, the emotional connection grew noticeably, as did commitment and motivation. After eleven months of preparation, the team lined up in Oceanside, California, in June 2016. Now they had to prove what they were capable of. As unknown outsiders, some of whom had very little road cycling experience, it was already doubtful whether they would even reach the finish line in Annapolis, Maryland. The human challenge of this sporting event, which lasted almost 10 days, quickly became apparent. The sweat poured, the muscles ached...but then the unthinkable happened. The underdog team from Thuringia won the race by five hours over the runner-up. Belief in the impossible made the seemingly impossible come true. If you'd like to learn more about the theory of success, I recommend the book 'How Dreams Come True' by Gerald Hüther.";
const synth = window.speechSynthesis;

const utterance = new SpeechSynthesisUtterance(
  ausgewählterText + window.getSelection()
);
utterance.lang = "en-US";
function readAloud() {
  synth.speak(utterance);
  const btn1 = document.querySelector(".btn1");
  btn1.style.fontSize = "1.6rem";
  btn1.innerHTML = `<marquee direction="up" scrollamount="1" height="500"
        >The story begins in East Germany.<br> Extreme athlete Sven Ole Müller, together with Nicole Bauer, a marathon runner, had set their minds on participating in a cycling race in the USA.<br> Although Nicole had never really ridden a racing bike for long at the time, she agreed to participate.<br><br> The cycling race was to be the toughest cycling race in the world, the Race Across America, which runs from the west coast of the USA to the east coast. A total of 5,000 kilometers must be completed. <br><br>They formed a team with two other athletes and began training. <br><br>But how do you approach such a project correctly?<br> Nicole came across the work of neurobiologist Gerald Hüther, who agreed to provide support. He repeatedly gave food for thought on how to build a functioning team. The basis was his theory of success, which he also presented in his later book, "How Dreams Come True." His approach is based on the idea that in an increasingly complex world, it is of the utmost importance that we define ourselves effectively and powerfully as a team, shaping our lives. <br><br>Time and again, there were problems during the preparations that made a successful participation in the cycle race seem a long way off. This was particularly due to the fact that the team members were more of an individual competitor. But gradually, the realization took hold that everyone would progress if they focused on each other. As a result, the emotional connection grew noticeably, as did commitment and motivation.<br><br> After eleven months of preparation, the team lined up at the start in Oceanside, California, in June 2016. <br>Now they had to prove what they could do. As unknown outsiders, some of whom had very little road cycling experience, it was already doubtful whether they would even reach the finish line in Annapolis, Maryland. <br><br>It quickly became apparent what a human challenge this sporting event, which lasted almost 10 days, represented. Sweat poured, muscles ached.<br><br>...but then the unthinkable happened. The Thuringian underdog team won the race by five hours over the runner-up. Belief in the impossible had made the seemingly impossible a reality. <br><br>If you'd like to learn more about the theory of success, I recommend the book "How Dreams Come True" by Gerald Hüther.
        <br>Klicke nun rechts auf den "weiter"-Button.</marquee>`;
}
function stopReading() {
  synth.cancel();
  window.location = "tillyEngl.html";
}
