const ausgewählterText =
  "The story begins in East Germany. The extreme athlete Sven Ole Müller, along with marathon runner Nicole Bauer, had set their minds on participating in a cycling race in the US. Although Nicole had never really ridden a racing bike at the time, she agreed to participate. The race that was in their minds was to be the toughest cycling race in the world. It is called Race Across America and it runs from the American west coast to the east coast, means a total distance of five thousand kilometers. They formed a team with two other athletes and began training. But how do you properly approach such a project? Nicole came across the work of neurobiologist Gerald Hüther, who agreed to provide support. He repeatedly offered suggestions on how to build a functioning team. The basis was his theory of success, which he also presented in his later book 'How Dreams Come True'. His approach is based on the idea that, in an increasingly complex world, it is of utmost importance that we define ourselves effectively and powerfully as a team, shaping our lives. Again and again, problems arose during the preparations that made a successful participation in the cycling race seem a distant prospect. This was primarily due to the fact that the team members were competing more as individual competitors. But gradually, they realized that everyone would progress if they focused on each other. Thus, the emotional connection grew noticeably, as did commitment and motivation. After eleven months of preparation, in June 2016, the team lined up in Oceanside, California. Now they had to prove what they were capable of. As unknown outsiders, some of whom had very little road cycling experience, it was already doubtful whether they would even reach the finish line in Annapolis, Maryland. The human challenge of this sporting event, which lasted almost 10 days, quickly became apparent. The sweat poured, the muscles ached...but then the unthinkable happened. The underdog team from Thuringia won the race by five hours over the runner-up. Belief in the impossible made the seemingly impossible come true. If you'd like to learn more about the theory of success, I recommend the book 'How Dreams Come True' by Gerald Hüther.";
const synth = window.speechSynthesis;

const utterance = new SpeechSynthesisUtterance(
  ausgewählterText + window.getSelection()
);
utterance.lang = "en-US";
function readAloud() {
  synth.speak(utterance);
  const btn1 = document.querySelector(".btn1");
  btn1.style.fontSize = "1.6rem";
  btn1.innerHTML = `<marquee direction="up" scrollamount="1" height="500"
        >The story begins in East Germany. <br> The extreme athlete Sven Ole Müller, along with marathon runner Nicole Bauer, had set their minds on participating in a cycling race in the US. Although Nicole had never really ridden a racing bike at the time, she agreed to participate.<br><br> The race that was in their minds was to be the toughest cycling race in the world. It is called Race Across America and it runs from the American west coast to the east coast, means a total distance of five thousand kilometers.<br><br> They formed a team with two other athletes and began training.<br><br> But how do you properly approach such a project? <br>Nicole came across the work of neurobiologist Gerald Hüther, who agreed to provide support. He repeatedly offered suggestions on how to build a functioning team. The basis was his theory of success, which he also presented in his later book 'How Dreams Come True'. His approach is based on the idea that, in an increasingly complex world, it is of utmost importance that we define ourselves effectively and powerfully as a team, shaping our lives. <br><br>Again and again, problems arose during the preparations that made a successful participation in the cycling race seem a distant prospect. This was primarily due to the fact that the team members were competing more as individual competitors. But gradually, they realized that everyone would progress if they focused on each other. Thus, the emotional connection grew noticeably, as did commitment and motivation.<br><br> After eleven months of preparation, in June 2016, the team lined up in Oceanside, California.<br> Now they had to prove what they were capable of. As unknown outsiders, some of whom had very little road cycling experience, it was already doubtful whether they would even reach the finish line in Annapolis, Maryland. <br><br>The human challenge of this sporting event, which lasted almost 10 days, quickly became apparent. The sweat poured, the muscles ached.<br><br>..but then the unthinkable happened. The underdog team from Thuringia won the race by five hours over the runner-up. Belief in the impossible made the seemingly impossible come true.<br><br> If you'd like to learn more about the theory of success, I recommend the book 'How Dreams Come True' by Gerald Hüther.
        <br>click on the continue button on the right side</marquee>`;
}
function stopReading() {
  synth.cancel();
  window.location = "tillyEngl.html";
}
